### ISSUE TITLE
Error, user management screen.

### ISSUE THREAD

**Issue by jesusluisfernando** [fredsdc/redmine_user_management#4]
Hi.

Error (log):

ActionView::Template::Error (undefined method `custom_field_tag_with_label' for #<#<Class:0x0000000008a057c8>:0x0000000008a34bb8>

**Comment by fredsdc** [comment]
I tried to debug this in a development environment. Let's go bit by bit, because I tried every kind of user custom field available and couldn't reproduce.

This error means that a custom user value from a user is failing to provide the custom_field_tag_with_label.

@user means your logger user, then the function recovers its custom_field_values (those you assign in Administration > Custom Fields > New > User).

It uses a function defined in app/helpers/custom_fields_helper.rb, that is used by various views, for example: app/views/users/_form.html.erb

The error seems to mean that one of the custom_field_values associated with @user is a class. It should be an item from class UserCustomField.

It just doesn't make any sense, maybe another plugin interference?

What's the request exactly?

On another note, there was an unapplied patch in this branch, please update.

**Comment by jesusluisfernando** [comment]
Hi, 

I resolved by adding the next code to controllers/user_managements_controller.rb



`class UserManagementsController < ApplicationController
  before_action :user_manager?
  before_action :get_permissions

  helper :users
  **helper :custom_fields
  include CustomFieldsHelper**
`

**Comment by fredsdc** [comment]
I see. The problem was the controller missing the helper function. It's strange, as the older code works for me here (development and production). I built a simple Redmine and just this plugin instalaltion, and it worked perfectly. I think maybe another plugin could be interfering or maybe it's a requirement for a different Rails/Ruby version.

By the way, maybe there is a better way to solve it, as you just need to use function custom_field_tag_with_label from the helper:

https://stackoverflow.com/questions/5130150/rails-how-to-use-a-helper-inside-a-controller

Glad to know you solved it.

**Comment by chrislockwood** [comment]
> Hi,
> 
> I resolved by adding the next code to controllers/user_managements_controller.rb
> ...

Thanks for this, we encountered exactly the same issue.

**Comment by fredsdc** [comment]
Updated master with [jesusluisfernando](https://github.com/jesusluisfernando) suggestion.
